# Generated by juwelier
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Juwelier::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: rspec-tapas 0.2.0 ruby lib

Gem::Specification.new do |s|
  s.name = "rspec-tapas".freeze
  s.version = "0.2.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0".freeze) if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib".freeze]
  s.authors = ["B\u0142a\u017Cej Kosmowski".freeze]
  s.date = "2018-06-27"
  s.description = "A selection of small rSpec extensions".freeze
  s.email = "b.kosmowski@selleo.com".freeze
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "VERSION",
    "lib/rspec-tapas.rb",
    "lib/rspec_tapas/all.rb",
    "lib/rspec_tapas/behavior_dsl.rb",
    "lib/rspec_tapas/date_helpers.rb",
    "lib/rspec_tapas/downloads_helpers.rb",
    "lib/rspec_tapas/feature_helpers.rb",
    "lib/rspec_tapas/get_message_part.rb",
    "lib/rspec_tapas/invoke_task.rb",
    "lib/rspec_tapas/json_response.rb",
    "lib/rspec_tapas/locators/find_table_row.rb",
    "lib/rspec_tapas/matchers/have_table_row.rb",
    "lib/rspec_tapas/stub_env.rb",
    "lib/rspec_tapas/view_page.rb",
    "rspec-tapas.gemspec"
  ]
  s.homepage = "http://github.com/Selleo/rspec-tapas".freeze
  s.licenses = ["MIT".freeze]
  s.rubygems_version = "2.6.14".freeze
  s.summary = "A selection of small rSpec extensions".freeze

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<shoulda>.freeze, [">= 0"])
      s.add_development_dependency(%q<rdoc>.freeze, ["~> 3.12"])
      s.add_development_dependency(%q<bundler>.freeze, ["~> 1.0"])
      s.add_development_dependency(%q<juwelier>.freeze, ["~> 2.1.0"])
      s.add_development_dependency(%q<simplecov>.freeze, [">= 0"])
    else
      s.add_dependency(%q<shoulda>.freeze, [">= 0"])
      s.add_dependency(%q<rdoc>.freeze, ["~> 3.12"])
      s.add_dependency(%q<bundler>.freeze, ["~> 1.0"])
      s.add_dependency(%q<juwelier>.freeze, ["~> 2.1.0"])
      s.add_dependency(%q<simplecov>.freeze, [">= 0"])
    end
  else
    s.add_dependency(%q<shoulda>.freeze, [">= 0"])
    s.add_dependency(%q<rdoc>.freeze, ["~> 3.12"])
    s.add_dependency(%q<bundler>.freeze, ["~> 1.0"])
    s.add_dependency(%q<juwelier>.freeze, ["~> 2.1.0"])
    s.add_dependency(%q<simplecov>.freeze, [">= 0"])
  end
end

