version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.5.1-node-browsers
        environment:
          RAILS_ENV: test
          BUNDLE_JOBS: "3"
          BUNDLE_RETRY: "3"
          BUNDLE_PATH: vendor/bundle

    steps:
      - checkout

      - restore_cache:
          keys:
            - gems-{{ checksum "Gemfile.lock" }}

      - run:
          name: Install dependencies
          command: |
            bundle check || bundle install

      - save_cache:
          key: gems-{{ checksum "Gemfile.lock" }}
          paths:
            - ./vendor/bundle

      - run:
          name: Run tests
          command: |
            mkdir /tmp/test-results
            TEST_FILES="$(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)"

            bundle exec rspec --format documentation \
                            --out /tmp/test-results/rspec.txt \
                            --format progress \
                            $TEST_FILES

      - store_test_results:
          path: /tmp/test-results

      - store_artifacts:
          path: /tmp/test-results
          destination: test-results
